name: Build and Deploy to Helios

on:
  workflow_dispatch:
    inputs:
      website_dir:
        description: "Папка со статикой (копируется в ~/public_html)"
        required: true
        default: "site/output"
      clean:
        description: "Очистить ~/public_html перед развёртыванием"
        required: true
        default: "true"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Nikola
        run: |
          python -m pip install --upgrade pip
          pip install "nikola[extras]"

      - name: Initialize Nikola site if missing
        run: |
          if [ ! -f site/conf.py ]; then
            nikola init -qd site
          fi

      - name: Publish report.md as a page
        run: |
          mkdir -p site/pages
          cp -f report.md site/pages/report.md

      - name: Build Nikola site
        working-directory: site
        run: nikola build

      - name: Set report.md as homepage
        working-directory: site
        run: |
          set -e
          REPORT_HTML="output/pages/report/index.html"
          if [ -f "$REPORT_HTML" ]; then
            cp "$REPORT_HTML" output/index.html
          else
            echo "Report page not found at $REPORT_HTML" >&2
            exit 1
          fi

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: site/output/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      HELIOS_HOST: helios.cs.ifmo.ru
      HELIOS_PORT: "2222"
      WEBSITE_DIR: ${{ github.event.inputs.website_dir || 'site/output' }}
    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: ${{ env.WEBSITE_DIR }}

      - name: Pack website into tar.gz
        run: |
          tar -czf site.tgz -C "${WEBSITE_DIR}" .

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Trust Helios host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${HELIOS_PORT}" "${HELIOS_HOST}" >> ~/.ssh/known_hosts

      - name: Upload archive
        env:
          HELIOS_USER: ${{ secrets.HELIOS_USER }}
          HELIOS_PASSWORD: ${{ secrets.HELIOS_PASSWORD }}
        run: |
          sshpass -p "${HELIOS_PASSWORD}" scp -P "${HELIOS_PORT}" site.tgz "${HELIOS_USER}@${HELIOS_HOST}:~/"

      - name: Deploy (unpack to ~/public_html)
        env:
          HELIOS_USER: ${{ secrets.HELIOS_USER }}
          HELIOS_PASSWORD: ${{ secrets.HELIOS_PASSWORD }}
          CLEAN: ${{ github.event.inputs.clean }}
        run: |
          sshpass -p "${HELIOS_PASSWORD}" ssh -p "${HELIOS_PORT}" "${HELIOS_USER}@${HELIOS_HOST}" "
            set -e
            mkdir -p ~/public_html
            if [ \"${CLEAN}\" = \"true\" ]; then
              rm -rf ~/public_html/*
            fi
            tar -xzf ~/site.tgz -C ~/public_html
            rm -f ~/site.tgz
          "

      - name: Done URL
        run: echo "Доступно по адресу https://se.ifmo.ru/~${{ secrets.HELIOS_USER }}/"


