name: Build and Deploy to Helios

on:
  workflow_dispatch:
    inputs:
      website_dir:
        description: "Папка со статикой (копируется в ~/public_html)"
        required: true
        default: "site/output"
      clean:
        description: "Очистить ~/public_html перед развёртыванием"
        required: true
        default: "true"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Nikola
        run: |
          python -m pip install --upgrade pip
          pip install "nikola[extras]"

      - name: Initialize Nikola site if missing
        run: |
          if [ ! -f site/conf.py ]; then
            nikola init -qd site
          fi

      - name: Prepare report and images
        run: |
          set -e
          mkdir -p site/pages
          # фикс ссылок на картинки: страница будет по адресу pages/report/
          # картинки публикуем в /images → относительный путь ../../images/ из pages/report/
          sed -E 's#\]\(images/#](../../images/#g; s#src=\"images/#src=\"../../images/#g' report.md > site/pages/report.md
          # копируем изображения в стандартную статику Nikola (files → /)
          mkdir -p site/files/images
          if [ -d images ]; then
            cp -R images/* site/files/images/ || true
          fi

      - name: Build Nikola site
        working-directory: site
        run: nikola build

      - name: Set homepage redirect to report page
        working-directory: site
        run: |
          mkdir -p output
          cat > output/index.html << 'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=pages/report/">
            <meta name="robots" content="noindex">
            <title>Redirecting…</title>
          </head>
          <body>
            <p>Redirecting to <a href="pages/report/">report</a>…</p>
            <script>location.replace('pages/report/');</script>
          </body>
          </html>
          EOF

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: site/output/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      HELIOS_HOST: helios.cs.ifmo.ru
      HELIOS_PORT: "2222"
      WEBSITE_DIR: ${{ github.event.inputs.website_dir || 'site/output' }}
    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: ${{ env.WEBSITE_DIR }}

      - name: Deploy with composite action
        uses: EnderWarik/helios-deploy-action@v0.0.1
        with:
          helios_user: ${{ secrets.HELIOS_USER }}
          helios_password: ${{ secrets.HELIOS_PASSWORD }}
          website_dir: ${{ env.WEBSITE_DIR }}
          clean: ${{ github.event.inputs.clean }}
          helios_host: ${{ env.HELIOS_HOST }}
          helios_port: ${{ env.HELIOS_PORT }}


