name: Build and Deploy to Helios

on:
  workflow_dispatch:
    inputs:
      website_dir:
        description: "Папка со статикой (копируется в ~/public_html)"
        required: true
        default: "site/output"
      clean:
        description: "Очистить ~/public_html перед развёртыванием"
        required: true
        default: "true"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Nikola
        run: |
          python -m pip install --upgrade pip
          pip install "nikola[extras]"

      - name: Initialize Nikola site if missing
        run: |
          set -e
          if [ ! -f site/conf.py ]; then
            mkdir -p site
            nikola init -qd _nikola_tmp
            mv _nikola_tmp/conf.py site/conf.py
            rm -rf _nikola_tmp
          fi

      - name: Configure site metadata and theme
        run: |
          set -e
          if ! grep -q "^THEME =" site/conf.py; then
            echo "THEME = 'custom'" >> site/conf.py
          else
            sed -i 's/^THEME = .*/THEME = '\''custom'\''/' site/conf.py || true
          fi
          sed -i 's/^BLOG_TITLE = .*/BLOG_TITLE = "EnderWar Site"/' site/conf.py || true
          sed -i 's/^BLOG_DESCRIPTION = .*/BLOG_DESCRIPTION = "Кастомная тема Nikola"/' site/conf.py || true
          if ! grep -q "^BLOG_AUTHOR =" site/conf.py; then
            echo "BLOG_AUTHOR = 'Алексей Москалёв'" >> site/conf.py
          else
            sed -i "s/^BLOG_AUTHOR = .*/BLOG_AUTHOR = 'Алексей Москалёв'/" site/conf.py || true
          fi
          sed -i 's/^DEFAULT_LANG = .*/DEFAULT_LANG = "ru"/' site/conf.py || true
          sed -i 's/^TIMEZONE = .*/TIMEZONE = "Europe/Moscow"/' site/conf.py || true
          if ! grep -q "^TYPOGRIFY =" site/conf.py; then
            echo "TYPOGRIFY = True" >> site/conf.py
          fi

      - name: Copy custom theme assets
        run: |
          mkdir -p site/themes/custom/assets/css site/themes/custom/assets/js
          cp -f site/themes/custom/assets/css/main.css site/assets/css/main.css || true
          cp -f site/themes/custom/assets/js/main.js site/assets/js/main.js || true

      - name: Prepare report and images
        run: |
          set -e
          mkdir -p site/pages
          sed -E 's#\]\(images/#](../../images/#g; s#src=\"images/#src=\"../../images/#g' report.md > site/pages/report.md
          mkdir -p site/files/images
          if [ -d images ]; then
            cp -R images/* site/files/images/ || true
          fi

      - name: Remove demo pages
        run: |
          set -e
          find site/pages -mindepth 1 -maxdepth 1 -type d ! -name home ! -name report -exec rm -rf {} + || true
          find site/pages -type f ! -name 'home.md' ! -name 'report.md' -delete || true

      - name: Build Nikola site
        working-directory: site
        run: |
          nikola clean -a || true
          nikola build

      - name: Set homepage redirect to author home page
        working-directory: site
        run: |
          mkdir -p output
          cat > output/index.html << 'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=pages/home/">
            <meta name="robots" content="noindex">
            <title>Redirecting…</title>
          </head>
          <body>
            <p>Redirecting to <a href="pages/home/">home</a>…</p>
            <script>location.replace('pages/home/');</script>
          </body>
          </html>
          EOF

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: site/output/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      HELIOS_HOST: helios.cs.ifmo.ru
      HELIOS_PORT: "2222"
      WEBSITE_DIR: ${{ github.event.inputs.website_dir || 'site/output' }}
    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: ${{ env.WEBSITE_DIR }}

      - name: Deploy with composite action
        uses: EnderWarik/helios-deploy-action@v0.0.1
        with:
          helios_user: ${{ secrets.HELIOS_USER }}
          helios_password: ${{ secrets.HELIOS_PASSWORD }}
          website_dir: ${{ env.WEBSITE_DIR }}
          clean: ${{ github.event.inputs.clean }}
          helios_host: ${{ env.HELIOS_HOST }}
          helios_port: ${{ env.HELIOS_PORT }}


